### PR TITLE
Upgrade to L5.6

### PR DESCRIPTION
**Pull request by egyptik**

### CODE REVIEW

**Comment by cretueusebiu** [comment]
Use composer require or update when updating these packages so it writes the correct lock file. Right now the tests will still run using the old packages.

**Comment by egyptik** [comment]
Ahh sorry. I did do that, but forgot to add the lock file to the commit. Just pushed it.

**Comment by cretueusebiu** [comment]
Also use the current branch when making these changes because it has some conflicts with the previous reverted commits.

**Comment by cretueusebiu** [comment]
Done in [4.1.0](https://github.com/cretueusebiu/laravel-vue-spa/releases/tag/4.1.0)

**Pull request closed without merging**
