### PR TITLE
Really 5.7 update

### PR DESCRIPTION
**Pull request by nguyentranchung**

### CODE REVIEW

**Comment by nguyentranchung** [comment]
I was try to using Laravel Mix 4, but failed!

**Comment by cretueusebiu** [comment]
Dynamic imports are not supported by Mix 4. Will have to wait for the next version with webpack 5.

**Comment by nguyentranchung** [comment]
This pull request latest laravel source code, and using laravel mix v2. You do not intend to consider merge it?

**Comment by cretueusebiu** [comment]
Sorry, I thought it was with the latest Mix. I'll take a look at the changes and merge it.

**Pull request closed without merging**
