### PR TITLE
Multiple enhancements and fixes / Repair and speeding up Travis CI builds

### LINKED ISSUE #163: HMR
It seems HMR in laravel-mix is broken since last year . I can't get it to work either , anyone found a solution for this particular repo ?

### PR DESCRIPTION
**Pull request by TemaSM**
- [x] Updated `sweetalert2` from `^7.19.3` to `^8.10.0`
- [x] Updated `vue-router`, `vue-i18n`, `jquery`, `sass`, `eslint-plugin-import`, `eslint-plugin-node`
- [x] Forced Laravel Dusk to use latest stable Chrome driver release (it was one of many reasons why Travis CI failing tests)
- [x] Enhanced Travis CI config - caching composer and npm, selfupdating composer, nodejs & npm to latest stable release during build, speeding up
- [x] Improved Laravel Dusk tests (fixed `no such element: Unable to locate element` and `element not interactable`)
- [x] Temporary disabled `mix.extract()`, because it's buggy with Webpack code-splitting/chunking mechanism (dynamic imports), see commit addf76d and related issue https://github.com/JeffreyWay/laravel-mix/issues/1889
- [x] Refactored routes file & fixed bugs of Laravel Mix 4 in webpack.mix.js file
- [x] Made HMR mode work great again, fixes #163
- [x] Regenerated `composer.lock` for freshness

### CODE REVIEW

**Comment by TemaSM** [comment]
Travis CI failing because Laravel Dusk has old Chrome driver, according to https://github.com/laravel/dusk/issues/641 issue.
So, there are incompatibility between  `chromedriver=2.45.615279` and `Unpacking google-chrome-stable (74.0.3729.108-1) over (62.0.3202.94-1)` as seen in Travis CI logs: `Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: Chrome version must be between 70 and 73`

**Comment by TemaSM** [comment]
According to Travis CI logs, eacf717 commit helped with Chrome and its driver to be in sync of versions to process Dusk tests

**Comment by TemaSM** [comment]
Finished with this PR, so waiting for your review @cretueusebiu

**Comment by TemaSM** [comment]
Finished with this PR, so waiting for your review @cretueusebiu

**Comment by cretueusebiu** [comment]
Thanks for all the great work! Will merge it soon.

**Comment by TemaSM** [comment]
Great to hear.
There's some minor updates available for npm packages, so will update them in an hour, just for better freshness of `laravel-vue-spa`.

**Comment by cretueusebiu** [comment]
I see you added `clean-webpack-plugin`, do you know if there's a way to clear the files after the build process, because right now when you run `npm run prod` it will delete the files and then generate new ones. So if your app is in production, for a few seconds while it builds, the js/css files will be missing.

**Comment by TemaSM** [comment]
Yeah, probably that's not good behavior. Will try to improve the way of clean rebuilding frontend & its assets. ETA: 1 hour.

**Comment by TemaSM** [comment]
Found bug with Laravel Mix and Webpack chunks (in `vue-router` routes definition file).
Fixing may take more time than I expected.

**Comment by cretueusebiu** [comment]
It's really a bummer with Laravel Mix 4. There seems to be so many new bugs introduced... Should we wait a bit more for a new release of Mix or maybe go back to v2 ?

**Comment by TemaSM** [comment]
I think we can stand with v4 by applying few codehacks for building process (fixed few already) and release new `laravel-vue-spa`.
But will remove them, just after Laravel Mix developers fix bugs.
If my attempts to fix will unsuccessful, then downgrading to v2 will be the best option I think.

**Comment by TemaSM** [comment]
I made it working fine, but there's still bug with HMR mode.
Can push commit, so you may test everything except HMR, till I trying to fix it too.

**Comment by cretueusebiu** [comment]
Great! HMR didn't worked before too, so that's not a problem.

**Comment by TemaSM** [comment]
That's it, fixed all bugs of Laravel Mix, even HMR mode 😃 
Waiting for your review @cretueusebiu

**Comment by cretueusebiu** [comment]
Great job with this PR! 

I've made some minor changes and will tag a new release soon.

**Pull request merged**
