### PR TITLE
Allow middleware to accept parameters

### PR DESCRIPTION
**Pull request by jimohalloran**
PR for code in issue #124 ...  @cretueusebiu I notice this change hasn't been included yet, so I've created this PR for you to help with the process.  This is just @imade-nl 's code form the ticket with a little additional documentation.

### CODE REVIEW

**Comment by Davides98** [comment]
So by editing these two files can I set different roles between the admin and user accounts?

**Comment by xazinji** [comment]
@Davides98 No, you will still need to use a package such as spatie/permission to actually have working roles/permissions and write the code for the store.

About the code, only thing I would change is use camelCase for the variables and make the role code pass eslint (spacing issues).

**Comment by Davides98** [comment]
@xazinji can you help me for this?

**Comment by jimohalloran** [comment]
This code is not intended to be a complete roles/permissions implementation.  A lot more work would still need to be done.  See my comment on #218 for a bit more detail.

**Comment by cretueusebiu** [comment]
Merged https://github.com/cretueusebiu/laravel-vue-spa/commit/07baf5b09ceb1a851deb670e2b3c3551a96118c9

**Comment by DasdWaller** [comment]
@cretueusebiu @jimohalloran You can create an example of this feature?

**Comment by cretueusebiu** [comment]
@DasdWaller https://www.github.com/cretueusebiu/laravel-vue-spa/tree/master/resources/js/middleware/role.js

**Pull request closed without merging**
